version: 2
jobs:
  one:
    docker:
      - image: circleci/node:10
    steps:
        - checkout
        - run: echo "Dave rules."
        - run: mkdir -p my_workspace
        - run: echo "Trying out workspaces" > my_workspace/echo-output
        - persist_to_workspace
          # Must be an absolute path, or relative path from working_directory
          root: my_workspace
          # Must be relative path from root
          paths: 
            - echo-output
  two:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: echo "Dave still rules"
      - attach_workspace:
        # Must be absolute path or relative path from working directory
          at: my_workspace
          
      - run: |
          if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
            echo "It worked!";
          else
            echo "No no no!"; exit 1
          fi
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two:
        requires:
          - one
