--- 
jobs: 
  one: 
    docker: 
      - 
        image: "circleci/node:10"
    steps: 
      - checkout
      - 
        run: "echo \"Dave rules.\""
      - 
        run: "mkdir -p my_workspace"
      - 
        run: "echo \"Trying out workspaces\" > my_workspace/echo-output"
      - 
        paths: 
          - echo-output
        persist_to_workspace: ~
        root: my_workspace
  two: 
    docker: 
      - 
        image: "circleci/node:10"
    steps: 
      - checkout
      - 
        run: "echo \"Dave still rules\""
      - 
        attach_workspace: 
          at: my_workspace
      - 
        run: |
            if [[ $(cat my_workspace/echo-output) == "Trying out workspaces" ]]; then
              echo "It worked!";
            else
              echo "No no no!"; exit 1
            fi
version: 2
workflows: 
  one_and_two: 
    jobs: 
      - one
      - 
        requires: 
          - one
        two: ~
  version: 2
