{
  "version": 2, 
  "jobs": {
    "two": {
      "docker": [
        {
          "image": "circleci/node:10"
        }
      ], 
      "steps": [
        "checkout", 
        {
          "run": "echo \"Dave still rules\""
        }, 
        {
          "attach_workspace": {
            "at": "my_workspace"
          }
        }, 
        {
          "run": "if [[ $(cat my_workspace/echo-output) == \"Trying out workspaces\" ]]; then\n  echo \"It worked!\";\nelse\n  echo \"No no no!\"; exit 1\nfi\n"
        }
      ]
    }, 
    "one": {
      "docker": [
        {
          "image": "circleci/node:10"
        }
      ], 
      "steps": [
        "checkout", 
        {
          "run": "echo \"Dave rules.\""
        }, 
        {
          "run": "mkdir -p my_workspace"
        }, 
        {
          "run": "echo \"Trying out workspaces\" > my_workspace/echo-output"
        }, 
        {
          "paths": [
            "echo-output"
          ], 
          "persist_to_workspace": null, 
          "root": "my_workspace"
        }
      ]
    }
  }, 
  "workflows": {
    "version": 2, 
    "one_and_two": {
      "jobs": [
        "one", 
        {
          "requires": [
            "one"
          ], 
          "two": null
        }
      ]
    }
  }
}